name: build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14, ubuntu-24.04, ubuntu-24.04-arm, windows-2022]

    permissions:
      contents: write

    steps:
      - name: Checkout own repository
        uses: actions/checkout@v4

      - name: Checkout Whisper-WebUI repository
        uses: actions/checkout@v4
        with:
          repository: jhj0517/Whisper-WebUI
          path: Whisper-WebUI

      - name: Build
        run: |
          if [[ "${{ matrix.os }}" == macos* ]]; then
            chmod +x ./build/mac.sh
            ./build/mac.sh
          elif [[ "${{ matrix.os }}" == ubuntu* ]]; then
            chmod +x ./build/ubuntu.sh
            ./build/ubuntu.sh
          else
            ./build/windows.bat
          fi

      - name: Build (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          chmod +x ./build/mac.sh
          ./build/mac.sh

      - name: Build (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          chmod +x ./build/ubuntu.sh
          ./build/ubuntu.sh

      - name: Build (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          .\build\windows.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./src-tauri/target/release/bundle/**/*

  # release:
  #   runs-on: ubuntu-24.04
  #   needs: build
  #   permissions:
  #     contents: write

  #   steps:
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         path: ./artifacts

  #     - name: Create Release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         files: |
  #           ./artifacts/macos-13-bundle/*.dmg
  #           ./artifacts/macos-14-bundle/*.dmg
  #           ./artifacts/ubuntu-24.04-bundle/*.deb
  #           ./artifacts/ubuntu-24.04-arm-bundle/*.deb
  #           ./artifacts/windows-2022-bundle/*.msi
