name: build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14, ubuntu-24.04, ubuntu-24.04-arm, windows-2022]

    permissions:
      contents: write

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Checkout own repository
        uses: actions/checkout@v4

      - name: Build
        shell: bash
        run: |
          ./build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./src-tauri/target/release/bundle/**/*

  # release:
  #   runs-on: ubuntu-24.04
  #   needs: build
  #   permissions:
  #     contents: write

  #   steps:
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         path: ./artifacts

  #     - name: Create Release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         files: |
  #           ./artifacts/macos-13-bundle/*.dmg
  #           ./artifacts/macos-14-bundle/*.dmg
  #           ./artifacts/ubuntu-24.04-bundle/*.deb
  #           ./artifacts/ubuntu-24.04-arm-bundle/*.deb
  #           ./artifacts/windows-2022-bundle/*.msi
