name: build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-15
    permissions:
      contents: write

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Checkout own repository
        uses: actions/checkout@v4

      - name: Download Whisper-WebUI
        run: |
          curl -L -o Whisper-WebUI-master.zip https://github.com/jhj0517/Whisper-WebUI/archive/refs/heads/master.zip
          unzip ./Whisper-WebUI-master.zip
          rm -rf ./Whisper-WebUI
          mv ./Whisper-WebUI-master ./Whisper-WebUI
          rm ./Whisper-WebUI-master.zip

      - name: Install vite dependencies
        run: |
          npm install

      - name: Install tauri dependencies
        run: |
          cd ./src-tauri
          cargo build

      - name: Install whisper dependencies
        run: |
          cd ./Whisper-WebUI
          sed -i '' 's|^\(--extra-index-url.*\)|# \1|' requirements.txt
          chmod +x ./Install.sh
          ./Install.sh

      - name: Build bundle
        run: |
          npm run tauri build -- --bundles dmg

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./src-tauri/target/release/bundle/dmg/*.dmg
