name: linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:

      - name: Checkout own repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install

      - name: Build app
        run: |
          npm run make

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_id }}
          files: |
            ./out/make/**/*.deb
            ./out/make/**/*.rpm
