name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    permissions:
      contents: write

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Checkout own repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install node dependencies
        run: |
          npm install

      - name: Install tauri dependencies
        run: |
          cd ./src-tauri
          cargo build

      - name: Install python
        run: |
          cd ./Whisper-WebUI
          python -m venv venv

      - name: Build app
        run: |
          npm run tauri build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./src-tauri/target/release/bundle/dmg/*.dmg
