name: macos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    permissions:
      contents: write

    steps:
      - name: Checkout own repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install node dependencies
        run: |
          npm install

      - name: Install tauri dependencies
        run: |
          cd ./src-tauri
          cargo build

      - name: Build app
        run: |
          npm run tauri build -- --bundles dmg --debug

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_id }}
          files: |
            ./src-tauri/target/**/bundle/dmg/*.dmg
